/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.58
 * Generated at: 2022-05-14 09:27:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/VanTrinh/Desktop/test/Land1/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/land2/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1644417328949L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<div class=\"row\">\n");
      out.write("	<div class=\"col-md-12 panel-warning\">\n");
      out.write("		<div class=\"content-box-header panel-heading\">\n");
      out.write("			<div class=\"panel-title \">Dashboard</div>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"msg\">\n");
      out.write("			<p style=\"color: green; font-size:20px\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"err\">\n");
      out.write("			<p style=\"color: red; font-size:20px\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${err }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"content-box-large box-with-header\">\n");
      out.write("			<div class=\"row\">\n");
      out.write("				<div class=\"col-md-4 col-sm-4 col-xs-4\">\n");
      out.write("					<div class=\"panel panel-back noti-box\">\n");
      out.write("						<span class=\"icon-box bg-color-green set-icon\"> <span\n");
      out.write("							class=\"glyphicon glyphicon-th-list\"></span>\n");
      out.write("						</span>\n");
      out.write("						<div class=\"text-box\">\n");
      out.write("							<p class=\"main-text\">\n");
      out.write("								<a class=\"fs-14\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/cat/index\" title=\"\">Quản lý danh mục</a>\n");
      out.write("							</p>\n");
      out.write("							<p class=\"text-muted\">Có ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${countCat }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" danh mục</p>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"col-md-4 col-sm-4 col-xs-4\">\n");
      out.write("					<div class=\"panel panel-back noti-box\">\n");
      out.write("						<span class=\"icon-box bg-color-blue set-icon\"> <span\n");
      out.write("							class=\"glyphicon glyphicon-book\"></span>\n");
      out.write("						</span>\n");
      out.write("						<div class=\"text-box\">\n");
      out.write("							<p class=\"main-text\">\n");
      out.write("								<a class=\"fs-14\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/land/index\" title=\"\">Quản lý bất động sản</a>\n");
      out.write("							</p>\n");
      out.write("							<p class=\"text-muted\">Có ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${countLand }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" bất động sản</p>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"col-md-4 col-sm-4 col-xs-4\">\n");
      out.write("					<div class=\"panel panel-back noti-box\">\n");
      out.write("						<span class=\"icon-box bg-color-brown set-icon\"> <span\n");
      out.write("							class=\"glyphicon glyphicon-user\"></span>\n");
      out.write("						</span>\n");
      out.write("						<div class=\"text-box\">\n");
      out.write("							<p class=\"main-text\">\n");
      out.write("								<a class=\"fs-14\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/user/index\" title=\"\">Quản lý người dùng</a>\n");
      out.write("							</p>\n");
      out.write("							<p class=\"text-muted\">Có ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${countUser }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" người dùng</p>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"col-md-4 col-sm-4 col-xs-4\">\n");
      out.write("					<div class=\"panel panel-back noti-box\">\n");
      out.write("						<span class=\"icon-box bg-color-blue set-icon\"> <span\n");
      out.write("							class=\"glyphicon glyphicon-envelope\"></span>\n");
      out.write("						</span>\n");
      out.write("						<div class=\"text-box\">\n");
      out.write("							<p class=\"main-text\">\n");
      out.write("								<a class=\"fs-14\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/contact/index\" title=\"\">Quản lý liên hệ</a>\n");
      out.write("							</p>\n");
      out.write("							<p class=\"text-muted\">Có ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${countContact }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" liên hệ</p>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"row\">\n");
      out.write("	<div class=\"col-md-6\">\n");
      out.write("		<div class=\"content-box-large\">\n");
      out.write("			<div class=\"panel-heading\">\n");
      out.write("				<div class=\"panel-title\">Chào mừng đến với trang quản trị</div>\n");
      out.write("\n");
      out.write("				<div class=\"panel-options\">\n");
      out.write("					<a href=\"#\" data-rel=\"collapse\"><i\n");
      out.write("						class=\"glyphicon glyphicon-refresh\"></i></a> <a href=\"#\"\n");
      out.write("						data-rel=\"reload\"><i class=\"glyphicon glyphicon-cog\"></i></a>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"panel-body\">\n");
      out.write("				... <br />\n");
      out.write("				<br />\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<div class=\"col-md-6\">\n");
      out.write("		<div class=\"row\">\n");
      out.write("			<div class=\"col-md-12\">\n");
      out.write("				<div class=\"content-box-header\">\n");
      out.write("					<div class=\"panel-title\">Hướng dẫn sử dụng</div>\n");
      out.write("\n");
      out.write("				</div>\n");
      out.write("				<div class=\"content-box-large box-with-header\">\n");
      out.write("\n");
      out.write("					... <br />\n");
      out.write("					<br />\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"row\">\n");
      out.write("			<div class=\"col-md-12\">\n");
      out.write("				<div class=\"content-box-header\">\n");
      out.write("					<div class=\"panel-title\">Nội quy</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"content-box-large box-with-header\">\n");
      out.write("					... <br />\n");
      out.write("					<br />\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
